version: "3.8"
services:
    hono-app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "${APP_PORT}:5000"
        environment:
            - PORT=${APP_PORT}
            - DATABASE_URL=${DATABASE_URL}
            - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
            - JWT_SECRET=${JWT_SECRET}
            - TOKEN_EXPIRATION=${TOKEN_EXPIRATION}
        restart: always
